/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
	implementation("commons-codec:commons-codec:1.19.0")
	implementation("commons-collections:commons-collections:3.2.2")
	implementation("commons-io:commons-io:2.20.0")
	implementation("org.apache.commons:commons-compress:1.28.0")
	implementation("org.apache.commons:commons-lang3:3.18.0")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

tasks.withType<Jar>().configureEach {
    archiveBaseName.set("FormatZip")
    archiveVersion.set("1.0.0")
    archiveExtension.set("jar")
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.xrea.s8.otokiti.formatzip.App"
        attributes["Class-Path"] = configurations.runtimeClasspath.get().joinToString(separator = " ") { file -> "libs/${file.name}" }
    }
}

tasks.register<Copy>("copyJar") {
    val libsDir = file("$buildDir/libs/libs")
    from(configurations.runtimeClasspath)
    into(libsDir)

	mustRunAfter("build")
}

tasks.named("jar") {
	mustRunAfter("copyJar")
}

tasks.register("generatedJar") {
	group = "build"
	description = "Cleans, builds, and copies the jar with dependencies."

    dependsOn("clean")
    dependsOn("build")
    dependsOn("copyJar")
    dependsOn("jar")
}